/**
 * OpenAI integration type definitions.
 *
 * This file defines the shared contract between the server-side OpenAI services
 * (transform, transcribe) and client-side hooks. Types are organized into five
 * groups: config, tool handling, stream events, inputs/outputs, and errors.
 *
 * The discriminated union pattern is used throughout (e.g. TransformStreamEvent,
 * TransformError) so consumers can narrow types via `event.type` / `error.code`
 * switch statements without type assertions.
 */

// --- Config ---

/** Supported input modalities for a transform config. Configs declare which they accept. */
export type TransformInputType = "text" | "image";

/**
 * Union of tool types supported by the OpenAI Responses API.
 *
 * - `web_search_preview` / `code_interpreter` / `file_search` are OpenAI hosted tools
 *   that the API executes automatically.
 * - `function` tools are custom: the model produces arguments, and we execute them
 *   server-side via the corresponding `ToolHandler` in `TransformConfig.toolHandlers`.
 */
export type TransformTool =
  | { type: "web_search_preview" }
  | { type: "code_interpreter" }
  | { type: "file_search"; vectorStoreIds: string[] }
  | {
      type: "function";
      name: string;
      description: string;
      /** JSON Schema describing the function's expected arguments. */
      parameters: Record<string, unknown>;
    };

/**
 * A complete configuration for an AI transform pipeline.
 *
 * Each config is registered by `id` in `configs/index.ts`. The `transform()` service
 * uses the config to build the OpenAI API request (model, system prompt, tools, params)
 * and to resolve function tool calls via `toolHandlers`.
 *
 * `inputTypes` determines what the UI should allow (text input, image upload, or both).
 */
export interface TransformConfig {
  id: string;
  model: string;
  systemPrompt: string;
  tools: TransformTool[];
  /** Declares which input modalities this config supports (used by UI to show/hide controls). */
  inputTypes: Set<TransformInputType>;
  maxOutputTokens?: number;
  temperature?: number;
  /**
   * Map of function tool name -> handler. When the model emits a function_call for a
   * tool name, the corresponding handler is invoked with the parsed arguments.
   * The handler must return a JSON string that becomes the tool output sent back to the model.
   */
  toolHandlers?: Record<string, ToolHandler>;
}

// --- Tool Handler ---

/**
 * Server-side handler for a custom function tool.
 * Receives parsed JSON arguments from the model and must return a JSON string result.
 * Errors thrown here are caught by the transform loop and reported as tool errors.
 */
export type ToolHandler = (
  args: Record<string, unknown>
) => Promise<string>;

// --- Stream Events ---

/**
 * Discriminated union of events emitted by the transform stream.
 *
 * The server-side `transform()` generator yields these events, which are serialized
 * as SSE `data:` lines by the `/api/ai/transform` route, and parsed on the client
 * by `useTransformStream`.
 *
 * Event lifecycle for a typical request:
 *   textDelta* -> done                           (no tool calls)
 *   functionCallStart -> functionCallDelta* -> functionCallDone -> textDelta* -> done  (with tool call)
 *
 * - `textDelta`: Incremental text token from the model's response.
 * - `functionCallStart`: The model has begun emitting a function call (name + callId).
 * - `functionCallDelta`: Incremental chunk of the function call's JSON arguments.
 * - `functionCallDone`: The function call's arguments are fully received.
 * - `imageUrl`: URL of an image generated by the code_interpreter tool.
 * - `error`: A non-fatal error (stream continues) or fatal error (followed by `done`).
 * - `done`: Terminal event — no more events will be emitted.
 */
export type TransformStreamEvent =
  | { type: "textDelta"; delta: string }
  | { type: "functionCallStart"; callId: string; name: string }
  | { type: "functionCallDelta"; callId: string; delta: string }
  | { type: "functionCallDone"; callId: string; name: string; arguments: string }
  | { type: "imageUrl"; url: string }
  | { type: "error"; message: string }
  | { type: "done" };

// --- Transform Input ---

/**
 * User-provided input for a transform request.
 * At least one of `text` or `imageUrl` must be provided.
 * The config's `inputTypes` determines which fields are valid.
 */
export interface TransformInput {
  text?: string;
  imageUrl?: string;
}

// --- Transcribe ---

/**
 * Result from the Whisper transcription API.
 * `language` and `duration` are only available when `response_format: "verbose_json"` is used.
 */
export interface TranscribeResult {
  text: string;
  /** ISO 639-1 language code detected by Whisper (e.g. "en", "es"). */
  language?: string;
  /** Duration of the audio in seconds. */
  duration?: number;
}

// --- Errors ---

/**
 * Structured error types for the transform pipeline.
 * Each variant has a `code` discriminator for programmatic handling and a human-readable `message`.
 *
 * - `apiError`: OpenAI API returned a non-2xx response.
 * - `configError`: Invalid or missing TransformConfig.
 * - `toolError`: A ToolHandler threw or returned invalid data.
 * - `streamError`: SSE stream failed mid-flight (network drop, parse failure).
 * - `inputError`: Client sent invalid or missing input fields.
 */
export type TransformError =
  | { code: "apiError"; message: string }
  | { code: "configError"; message: string }
  | { code: "toolError"; message: string }
  | { code: "streamError"; message: string }
  | { code: "inputError"; message: string };

/**
 * Structured error types for the transcription endpoint.
 * - `apiError`: Whisper API returned an error.
 * - `formatError`: The uploaded file is not a supported audio format.
 */
export type TranscribeError =
  | { code: "apiError"; message: string }
  | { code: "formatError"; message: string };

/**
 * Structured error types for the client-side audio recorder hook.
 * - `permissionDenied`: User denied microphone access (or browser blocked it).
 * - `recordingFailed`: MediaRecorder threw during start/stop.
 * - `noRecording`: Attempted to stop when no recording was active.
 */
export type AudioRecorderError =
  | { code: "permissionDenied"; message: string }
  | { code: "recordingFailed"; message: string }
  | { code: "noRecording"; message: string };
